# environments/project-gke/todo-app-patch.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-dep
spec:
  template:
    spec:
      containers:
      - name: todo-app-container
        image: asia-south1-docker.pkg.dev/dwk-gke-480015/dwk-gke-repository/todo-app:${{ github.sha }}
