apiVersion: batch/v1
kind: Job
metadata:
  name: pingpong-db-init
  namespace: exercises
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: init-db
        image: postgres:15-alpine
        command: ["sh", "-c"]
        args:
        - |
          echo "Waiting for PostgreSQL service..."
          until pg_isready -h postgresql-db-svc.exercises.svc.cluster.local -p 5432 -U testdbuser; do
            echo "PostgreSQL not ready - waiting (5s)..."
            sleep 5
          done
          echo "PostgreSQL ready - creating pingpong_counter table..."
          PGPASSWORD=$POSTGRES_PASSWORD psql -h postgresql-db-svc.exercises.svc.cluster.local -U testdbuser -d testdb -c "
            CREATE TABLE IF NOT EXISTS pingpong_counter (
                id SERIAL PRIMARY KEY,
                value INTEGER NOT NULL DEFAULT 0
            );
            INSERT INTO pingpong_counter (id, value) VALUES (1, 0) ON CONFLICT (id) DO NOTHING;
            SELECT 'Table ready!' as status;
          " && echo '✅ DB INITIALIZATION COMPLETE'
        envFrom:
        - configMapRef:
            name: postgres-db-config
        env:  # ADD THIS - Password from ConfigMap
        - name: POSTGRES_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: postgres-db-config
              key: POSTGRES_PASSWORD
