apiVersion: v1
kind: Pod
metadata:
  name: wikipedia-pod
  namespace: exercises
  labels:
    app: wikipedia
spec:
  # Init Container: Fetch Kubernetes page ONCE at startup
  # ---------------------------------------------------------
  initContainers:
  - name: init-kubernetes-wiki
    image: curlimages/curl:8.4.0
    command: 
    - sh
    - -c
    - |
      curl -s https://en.wikipedia.org/wiki/Kubernetes \
        | sed 's/href="\/wiki\//href="https:\/\/en.wikipedia.org\/wiki\//g' \
        > /shared/index.html
    volumeMounts:
    - name: www-data
      mountPath: /shared
  
  # Main container: Nginx serves shared volume
  # ---------------------------------------------------------  
  containers:
  - name: nginx
    image: nginx:1.27-alpine
    ports:
    - containerPort: 80
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: www-data
  
  # Sidecar 
  # apps/wikipedia/wikipedia-pod.yaml → wiki-refresher
  - name: wiki-refresher
    image: busybox:1.36
    securityContext:
      runAsUser: 0  # Root for mkdir + crond
    command:
    - sh
    - -c
    - |
      # Initial download
      echo "$(date): Initial random wiki download"
      wget --no-check-certificate -q -O /shared/random.html \
        --header='Accept: text/html' https://en.wikipedia.org/wiki/Special:Random && \
      sed -i 's|href=\"/wiki/|href=\"https://en.wikipedia.org/wiki/|g' /shared/random.html

      # Random 5-15 minutes (300-900 seconds)
      while true; do
        INTERVAL=$((RANDOM % 601 + 300))  # 300-900s = 5-15min
        echo "$(date): Next refresh in ${INTERVAL}s"
        sleep ${INTERVAL}
        echo "$(date): Refreshing random wiki"
        wget --no-check-certificate -q -O /shared/random.html \
          --header='Accept: text/html' https://en.wikipedia.org/wiki/Special:Random && \
        sed -i 's|href=\"/wiki/|href=\"https://en.wikipedia.org/wiki/|g' /shared/random.html
        echo "$(date): Refreshing random wiki done"
      done
    volumeMounts:
    - mountPath: /shared
      name: www-data

  
  volumes:
  - name: www-data
    emptyDir: {}
  
  # Sidecar: Refresh random wiki every 5-15min
  # ---------------------------------------------------------  
  # - name: wiki-refresher
  #   image: curlimages/curl:8.4.0
  #   command:
  #   - sh
  #   - -c
  #   - |
  #     while true; do
  #       # Random delay 5-15min (300-900s)
  #       sleep $((300 + RANDOM % 600))
  #       # Fetch random wiki page
  #       curl -s https://en.wikipedia.org/wiki/Special:Random \
  #         | sed 's/href="\/wiki\//href="https:\/\/en.wikipedia.org\/wiki\//g' \
  #         > /shared/random.html
  #       echo "$(date): Refreshed random wiki -> /shared/random.html"
  #     done
  #   volumeMounts:
  #   - name: www-data
  #     mountPath: /shared

---
# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: nginx-config
#   namespace: exercises
# data:
#   nginx.conf: |
#     events {}
#     http {
#       server {
#         listen 80;
#         root /usr/share/nginx/html;
#         index index.html random.html;
#         location / {
#           try_files $uri $uri/ =404;
#         }
#       }
#     }
# ---