# resources-patch - Exercise 3.11 Resource Limits
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql-db
  namespace: project
spec:
  template:
    spec:
      containers:
      - name: postgresql-db
        resources:
          requests:
            cpu: "50m"
            memory: "128Mi"
          limits:
            cpu: "250m"
            memory: "256Mi"
