# resources-patch - Exercise 3.11 Resource Limits
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-backend-dep
  namespace: project
spec:
  template:
    spec:
      containers:
      - name: todo-backend-container
        resources:
          requests:
            cpu: "10m"
            memory: "64Mi"
          limits:
            cpu: "100m"
            memory: "128Mi"
